// Generated by scripts/fetch-photos.mjs — do not edit by hand.
export interface PhotoCredit {
    file: string
    author: string
    license: string
    sourceUrl: string
}

export const photoCredits: Record<string, PhotoCredit> = {
    aal: {
        file: 'Anguilla_anguilla.jpg',
        author: 'GerardM',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Anguilla_anguilla.jpg',
    },
    aesche: {
        file: 'Grayling Thymallus thymallus.JPG',
        author: 'High Plains Grifter',
        license: 'CC BY-SA 4.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Grayling_Thymallus_thymallus.JPG',
    },
    aland: {
        file: 'LeuciscusIdusHead.JPG',
        author: 'Piet Spaans',
        license: 'CC BY 2.5',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:LeuciscusIdusHead.JPG',
    },
    bachforelle: {
        file: 'Bachforelle_Zeichnung.jpg',
        author: 'Duane Raver, U.S. Fish and Wildlife Service',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Bachforelle_Zeichnung.jpg',
    },
    barbe: {
        file: 'Barbe_Tiergarten_Schoenbrunn_(cropped).jpg',
        author: 'Linie29',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Barbe_Tiergarten_Schoenbrunn_(cropped).jpg',
    },
    barsch: {
        file: 'Perca_fluviatilis.jpg',
        author: 'The original uploader was GerardM at Dutch Wikipedia.',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Perca_fluviatilis.jpg',
    },
    bitterling: {
        file: 'BittervoornRhodeusAmarusVrouwtje.JPG',
        author: 'Viridiflavus',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:BittervoornRhodeusAmarusVrouwtje.JPG',
    },
    blei: {
        file: 'Carp_bream.jpg',
        author: 'Микова Наталия',
        license: 'Public domain',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Carp_bream.jpg',
    },
    doebel: {
        file: 'Squalius_cephalus_Prague_Vltava_2.jpg',
        author: 'Karelj',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Squalius_cephalus_Prague_Vltava_2.jpg',
    },
    giebel: {
        file: 'Carassius_gibelio_2008_G3.jpg',
        author: 'George Chernilevsky',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Carassius_gibelio_2008_G3.jpg',
    },
    'grosse-maraene': {
        file: 'Coregonus_lavaretus_maraena_1.jpg',
        author: 'Apple2000',
        license: 'CC BY 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Coregonus_lavaretus_maraena_1.jpg',
    },
    gruendling: {
        file: 'LS_09776a_gruendling.jpg',
        author: 'Lorenz Seebauer',
        license: 'CC BY-SA 4.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:LS_09776a_gruendling.jpg',
    },
    guester: {
        file: 'Blicca_bjoerkna_underwater.jpg',
        author: 'Lorenz Seebauer',
        license: 'CC BY-SA 4.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Blicca_bjoerkna_underwater.jpg',
    },
    hecht: {
        file: 'Europäischer_Hecht.jpg',
        author: 'HalbsHännile',
        license: 'CC BY-SA 4.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Europ%C3%A4ischer_Hecht.jpg',
    },
    karausche: {
        file: 'Männliche_Karausche.jpg',
        author: 'Swaggo42',
        license: 'CC BY-SA 4.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:M%C3%A4nnliche_Karausche.jpg',
    },
    karpfen: {
        file: 'Common_carp.jpg',
        author: 'USFWS',
        license: 'Public domain',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Common_carp.jpg',
    },
    kaulbarsch: {
        file: 'Gymnocephalus_cernuus_Pärnu_River_Estonia_2010-01-06.jpg',
        author: 'Tiit Hunt',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Gymnocephalus_cernuus_P%C3%A4rnu_River_Estonia_2010-01-06.jpg',
    },
    lachs: {
        file: 'Atlantischer_Lachs.jpg',
        author: 'Hartley, William W.',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Atlantischer_Lachs.jpg',
    },
    meerforelle: {
        file: 'Wst_meerforelle_stoer_001.jpg',
        author: 'No machine-readable author provided. Wolfgang Striewski assumed (based on copyright claims).',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Wst_meerforelle_stoer_001.jpg',
    },
    nase: {
        file: 'Chondrostoma_nasus_(aka).jpg',
        author: 'André Karwath aka Aka',
        license: 'CC BY-SA 2.5',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Chondrostoma_nasus_(aka).jpg',
    },
    ploetze: {
        file: 'Blausteinsee_Tierwelt_03.jpg',
        author: 'Creator: Ullrich MühlhoffUploader: Cornelius Herget',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Blausteinsee_Tierwelt_03.jpg',
    },
    quappe: {
        file: 'Trüsche_Zürichsee.jpg',
        author: 'Jeolme',
        license: 'CC BY-SA 4.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Tr%C3%BCsche_Z%C3%BCrichsee.jpg',
    },
    rapfen: {
        file: 'Aspius_aspius_Prague_Vltava_1_(cropped).jpg',
        author: 'Karelj',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Aspius_aspius_Prague_Vltava_1_(cropped).jpg',
    },
    regenbogenforelle: {
        file: 'Rainbow_Trout_(Oncorhynchus_mykiss)_(cropped).jpg',
        author: 'Liquid Art',
        license: 'CC BY-SA 4.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Rainbow_Trout_(Oncorhynchus_mykiss)_(cropped).jpg',
    },
    rotfeder: {
        file: 'Scardinius_erythropthalmus_2009_G1.jpg',
        author: 'George Chernilevsky',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Scardinius_erythropthalmus_2009_G1.jpg',
    },
    schlammpeitzger: {
        file: 'Misgurnus_fossilis_2009_G1.jpg',
        author: 'George Chernilevsky',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Misgurnus_fossilis_2009_G1.jpg',
    },
    schleie: {
        file: 'Tinca_tinca_Prague_Vltava_1.jpg',
        author: 'Karelj',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Tinca_tinca_Prague_Vltava_1.jpg',
    },
    seeforelle: {
        file: 'Salmo trutta.jpg',
        author: 'Eric Engbretson for U.S. Fish and Wildlife Service',
        license: 'Public domain',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Salmo_trutta.jpg',
    },
    steinbeisser: {
        file: 'Steinbeisser_001.jpg',
        author: 'J.C. Harf (User Wiki-Harfus on de.wikipedia)',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Steinbeisser_001.jpg',
    },
    stoer: {
        file: 'Acipenser_oxyrhynchus.jpg',
        author: 'Duane Raver/U.S. Fish and Wildlife Service',
        license: 'Public domain',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Acipenser_oxyrhynchus.jpg',
    },
    ukelei: {
        file: 'A_large_common_bleak.jpg',
        author: 'Peter van der Sluijs',
        license: 'CC BY-SA 3.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:A_large_common_bleak.jpg',
    },
    wels: {
        file: 'Freischwimmender_Wels.jpg',
        author: 'HalbsHännile',
        license: 'CC BY-SA 4.0',
        sourceUrl:
            'https://commons.wikimedia.org/wiki/File:Freischwimmender_Wels.jpg',
    },
    zander: {
        file: 'Zander.jpg',
        author: 'Unbekannt / unknown',
        license: 'Public domain',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Zander.jpg',
    },
}
